title: "Stephen Jiang - Stochastic Spinnakers"
description: "The Intersection of Software Engineering, Finance, Data Science, and Economics"
masthead_title: "Stochastic Spinnakers"
url: "https://stephenjiang.io"
baseurl: ""  # Leave empty for user/organization site

theme: minimal-mistakes-jekyll

minimal_mistakes_skin: "dark"

plugins:
  - jekyll-include-cache
  - jekyll-feed 

markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Author
author:
  name: "Stephen Jiang"
  avatar: "/assets/images/avatar.jpg"
  bio: "The Intersection of Software Engineering, Finance, Data Science, and Economics"
  location: "Earth"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Stephen-Jiang"

# Pagination (home page only)
paginate: 10
paginate_path: "/page:num/"

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Layout defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      read_time: true
      comments: false
      author_profile: true
      classes: wide
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true

atom_feed:
  path: "feed.xml"  # default
  posts_limit: 10  # default
